name: Build and Deploy

env:
  APP_NAME: valkyr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Docker image artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $APP_NAME:latest
        docker save $APP_NAME:latest | gzip > $APP_NAME.tar.gz
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: |
          $APP_NAME.tar.gz
          ci/deploy.sh

  deploy:
    name: Deploys Docker image to server
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: artifact
    - name: Deploy Docker image
      shell: bash
      env:
        SSH_HOST: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
      run: |
        ls
        echo "${{ secrets.SSH_KEY }}" > ./key
        chmod 0600 ./key
        scp -o StrictHostKeyChecking=no -i ./key \
          $APP_NAME.tar.gz $SSH_HOST:images/
        ssh -o StrictHostKeyChecking=no -i ./key $SSH_HOST \
          'bash -s' < ci/deploy.sh
